
stages:
  - testing
  - docs
  - publish

# shorthand for testing
.test_template: &template
  image: alejandroastudillo/tasho-base
  tags:
    - docker
  before_script:
    - source activate tasho-base
    - rm -rf .pip
    - rm -r /tmp/*
    - pip --no-cache-dir install casadi rockit-meco sphinx-gallery sphinx_rtd_theme coverage nose pybullet
    - python setup.py install
    - rm -r /tmp/*
  cache:
    paths:
      - .pip

testing:unittests:
  stage: testing
  <<: *template
  script:
    - nosetests --with-coverage --cover-html --cover-package=tasho
  artifacts:
    paths:
      - cover

testing:examples:
  stage: testing
  <<: *template
  script:
    - find examples -name "*.py" -not -path "*/wip/*" | xargs -n 1 python

docs:sphinx:
  stage: docs
  <<: *template
  dependencies:
    - testing:unittests
  script:
    - cd docs && mkdir -p apidoc
    - sphinx-apidoc -f -o ./apidoc/ ../tasho/
    - make html
  artifacts:
    paths:
      - docs/build
  only:
    - master


pages:
  stage: publish
  tags:
    - pages
  dependencies:
    - testing:unittests
    - docs:sphinx
  script:
    - mkdir public
    - cp -R ./cover ./public/coverage
    - cp -R ./docs/build/html/* ./public/
  artifacts:
    paths:
      - public
  only:
    - master
